name: 'Update Repository Description'
description: 'Read package.json and update description on github repository page.'
inputs:
  repo-token:
    description: 'github token'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'chevron-up'
  color: 'green'
